### ISSUE TITLE
Volume creating exception

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#8] opened 2018-08-31 21:55 UTC
# Bug

## Versions

- linstor `0.6.0`
- linstor-proxmox plugin `2.9.0`
- proxmox-ve `5.2`
- drbd kernel `9.0.15`
- drbdadm `9.5.0`
- deiver: lvm

## Details

Hi I'm testing linstor-proxmox plugin, and I have some problems:

When I try to create lxc container, I have the next output:
```
SUCCESS:
Description:
    New resource definition 'vm-555-disk-1' created.
Details:
    Resource definition 'vm-555-disk-1' UUID is: e82d64c5-3a83-48d1-b9e7-6bb342320f0b
SUCCESS:
Description:
    Resource definition 'vm-555-disk-1' modified.
Details:
    Resource definition 'vm-555-disk-1' UUID is: e82d64c5-3a83-48d1-b9e7-6bb342320f0b
SUCCESS:
    New volume definition with number '0' of resource definition 'vm-555-disk-1' created.
SUCCESS:
Description:
    Resource 'vm-555-disk-1' successfully autoplaced on 2 nodes
Details:
    Used storage pool: 'data'
    Used nodes: 'pve1-2', 'pve1-3'
mke2fs 1.43.4 (31-Jan-2017)
Could not open /dev/drbd/by-res/vm-555-disk-1/0: Wrong medium type
WARNING: Satellite connection lost
error with cfs lock 'storage-drbdstorage': Could not remove vm-555-disk-1: exit code 11
TASK ERROR: command 'mkfs.ext4 -O mmp -E 'root_owner=0:0' /dev/drbd/by-res/vm-555-disk-1/0' failed: exit code 1
```

Experienced, I found out that in the moment of crating filesystem both devices are in **Secondary**

After that I can't create any new devices, because autoplacing is not working anymore:

```
Reported error:
===============

Category:                           RuntimeException
Class name:                         AccessToDeletedDataException
Class canonical name:               com.linbit.linstor.AccessToDeletedDataException
Generated at:                       Method 'checkDeleted', Source file 'VolumeData.java', Line #416

Error message:                      Access to deleted volume

Error context:
    Registration of auto-placing resource: 'vm-333-disk-1' failed due to an unknown exception.
```

Full stacktrace: [ErrorReport-5B89B429-000001.log](https://github.com/LINBIT/linstor-server/files/2341719/ErrorReport-5B89B429-000001.log)

I have thee nodes cluster and the next config:
```
drbd: drbdstorage
   content images,rootdir
   redundancy 2
   controller 10.28.36.172
   controllervm 103
```

**Comment by ghernadi** [comment] 2018-09-03 06:40
Thanks for the report, that looks like we are forgetting to delete the volume from the `FreeSpaceManager`'s internal volumes-list. Will investigate further. 
The question I am more interested in is what happened that the volume was deleted in first place? Could you please also attach the ErrorReport-5B89B429-000000.log? Hopefully that gives some insight why both drbd-resources were secondary when the plugin tried to create the FS.

**Comment by kvaps** [comment] 2018-09-03 16:10
Sure, please
[ErrorReport-5B89B429-000000.log](https://github.com/LINBIT/linstor-server/files/2346146/ErrorReport-5B89B429-000000.log)

**Comment by ghernadi** [comment] 2018-09-04 06:40
Unfortunately none of the two error reports give more insight in the actually error.

Your first post shows that you create a new Resource-Definition, a new Volume-Definition and the controller successfully (!) auto-places the 2 resources in storage pool 'data' on nodes 'pve1-2', 'pve1-3'. 
For whatever reason one of the satellites fail to create the FS on the newly create volume. We would need other ErrorReports for that (from the satellite-node, not from controller). 

Another question is the following: The two ErrorReports you gave me complain about access to a deleted volume. I would be very interested in how that is possible. 

What steps did you do before the auto-place failed with the shown error? Did you tried some auto-places before and deleted them again? Did some errors occur which didn't seemed too big of an issue? 

If a volume claims that it is already deleted, it should already be deleted from the database. That means, you can try restarting the controller which will reload all data from the database. That might fix your current issue, allowing you to use the auto-place feature again. 

(I'm still interested in what actually happened / how you got into this situation :) )

**Comment by kvaps** [comment] 2018-09-05 13:37
OK, I was updated linstor to the latest version on all nodes `0.6.2`

I found out that out satellites is going OFFLINE immediately after creating new resources on them.

Example: I've prepared new VM in proxmox. It's exactly VM not container so not requires filesystem creation.
So drbd devices was prepared but both in secondary, because both nodes was marked as OFFLINE.

Then I do the next procedure:

* Stop `linstor-controller.service`
* Restart `linstor-satelitte.service` on all nodes
* Start `linstor-controller.service`
* Watch whats changed

There is no any error reports, `linstor-satellite` just shows the next things into the log, after I bring up my `linstor-controller`:

```
15:28:56.491 [MainWorkerPool-1] INFO  LINSTOR/Satellite - Controller connected and authenticated
15:28:56.651 [MainWorkerPool-2] INFO  LINSTOR/Satellite - Node 'pve1-2' created.
15:28:56.652 [MainWorkerPool-2] INFO  LINSTOR/Satellite - Node 'pve1-3' created.
15:28:56.653 [MainWorkerPool-2] INFO  LINSTOR/Satellite - Storage pool 'DfltDisklessStorPool' created.
15:28:56.653 [MainWorkerPool-2] INFO  LINSTOR/Satellite - Storage pool 'data' created.
15:28:56.659 [MainWorkerPool-2] INFO  LINSTOR/Satellite - Resource 'vm-1231-disk-1' created for node 'pve1-2'.
15:28:56.659 [MainWorkerPool-2] INFO  LINSTOR/Satellite - Resource 'vm-1231-disk-1' created for node 'pve1-3'.
```

No exceptions no errors, nothing more

**From the controller side:**
*Nodes marked as `Connecting` after start up then immideately going `OFFLINE`.
*The node which is not holding drbd resource is always `ONLINE`

**Comment by kvaps** [comment] 2018-09-05 13:40
UPD: after I stopped linstor-sattelite process I've got the next output:
```
15:38:53.242 [Thread-10] INFO  LINSTOR/Satellite - Shutdown in progress
15:38:53.248 [StltWorkerPool_0000] ERROR LINSTOR/Satellite - Initialization of storage for resource 'vm-1231-disk-1' volume 0 failed [Report number 5B8FDA04-000001]

15:38:53.248 [MainWorkerPool-7] INFO  LINSTOR/Satellite - Controller connected and authenticated
15:38:53.248 [MainWorkerPool-1] INFO  LINSTOR/Satellite - Controller connected and authenticated
15:38:53.249 [MainWorkerPool-2] INFO  LINSTOR/Satellite - Controller connected and authenticated
15:38:53.249 [Thread-10] INFO  LINSTOR/Satellite - Shutting down service instance 'DeviceManager' of type DeviceManager
15:38:53.249 [Thread-10] INFO  LINSTOR/Satellite - Waiting for service instance 'DeviceManager' to complete shutdown
15:38:53.249 [Thread-10] INFO  LINSTOR/Satellite - Shutting down service instance 'DrbdEventPublisher-1' of type DrbdEventPublisher
15:38:53.249 [Thread-10] INFO  LINSTOR/Satellite - Waiting for service instance 'DrbdEventPublisher-1' to complete shutdown
15:38:53.249 [Thread-10] INFO  LINSTOR/Satellite - Shutting down service instance 'DrbdEventService-1' of type DrbdEventService
15:38:53.249 [Thread-10] INFO  LINSTOR/Satellite - Waiting for service instance 'DrbdEventService-1' to complete shutdown
15:38:53.249 [Thread-10] INFO  LINSTOR/Satellite - Shutting down service instance 'FileEventService' of type FileEventService
15:38:53.249 [MainWorkerPool-8] ERROR LINSTOR/Satellite - Command 'vgs hv3 -o vg_free --units k --noheadings --nosuffix' returned with exitcode 130. 

Standard out: 


Error message: 

 [Report number 5B8FDA04-000000]

15:38:53.249 [Thread-10] INFO  LINSTOR/Satellite - Waiting for service instance 'FileEventService' to complete shutdown
15:38:53.249 [Thread-10] INFO  LINSTOR/Satellite - Shutting down service instance 'NetComService' of type NetComService
15:38:53.250 [Thread-10] INFO  LINSTOR/Satellite - Waiting for service instance 'NetComService' to complete shutdown
15:38:53.250 [Thread-10] INFO  LINSTOR/Satellite - Shutting down service instance 'TimerEventService' of type TimerEventService
15:38:53.250 [Thread-10] INFO  LINSTOR/Satellite - Waiting for service instance 'TimerEventService' to complete shutdown
15:38:53.250 [Thread-10] INFO  LINSTOR/Satellite - Shutdown complete
```
[5B8FDA04-000000.log](https://github.com/LINBIT/linstor-server/files/2352955/5B8FDA04-000000.log)

**Comment by kvaps** [comment] 2018-09-05 13:42
Looks like the reason is hunged `vgs hv3 -o vg_free --units k --noheadings --nosuffix` command,
but without linstor it is working correctly, but somehow slow:

```
# time vgs hv3 -o vg_free --units k --noheadings --nosuffix
  880820224.00

real    0m10.149s
user    0m0.006s
sys     0m0.000s
```

**Comment by ghernadi** [comment] 2018-09-05 13:46
This one really bothers me:

```
15:38:53.248 [MainWorkerPool-7] INFO LINSTOR/Satellite - Controller connected and authenticated 
15:38:53.248 [MainWorkerPool-1] INFO LINSTOR/Satellite - Controller connected and authenticated 
15:38:53.249 [MainWorkerPool-2] INFO LINSTOR/Satellite - Controller connected and authenticated
```
within 2 ms 3 different threads reported "Controller connected and authenticated". Are you sure that those satellites are only registered within ONE currently active and running controller node?

**Comment by rck** [comment] 2018-09-05 13:52
For LVM, as it bit me today on xen-server: It is really important to set filterns in `lvm.conf`. I already had many linstor "issues" on different platforms, which were related to LVM. Slow `lvs` usually was a sign for that. Then I usually set filters allowing the pv devices and ignore everything else. Usually then everything is fine.

**Comment by kvaps** [comment] 2018-09-05 13:55
Ok, it seems I found out where is problem:

```
# pstree -l 2158200                                                                                                                                                                                                               
java─┬─drbdsetup                                                                                                                                                                                
     ├─vgs                                                                                                                                                              
     └─51*[{java}]     
# ps aux | grep vgs
root     2158869  0.0  0.0  35712  4744 pts/3    D+   15:45   0:00 vgs -o vg_name --noheadings
root     2158872  0.0  0.0  34040  4652 ?        S    15:45   0:00 /sbin/vgscan --ignorelockingfailure --mknodes
# time vgs -o vg_name --noheadings
  hv3

real    0m20.556s
user    0m0.000s
sys     0m0.006s
```

I used some iscsi devices on this testing environmnt previously, seems they wasn't disconnected properly.
Thats why this lvm comands executing so long. Presume linstor wasn't expect that, or was it?

**Comment by ghernadi** [comment] 2018-09-05 13:57
Linstor's default timeout for external commands is 45 seconds.

**Comment by kvaps** [comment] 2018-09-05 13:58
No, my iscsi device is working fine.

>Are you sure that those satellites are only registered within ONE currently active and running controller node?

I'm sure, but I'll check it via tcpdump now

**Comment by kvaps** [comment] 2018-09-05 14:11
No other connections, I also try strace, but it showing nothing because of fork process..
It there any debugging option for satellite?

**Comment by kvaps** [comment] 2018-09-05 14:12
If i restart controller, it shows node like `Connected` for few second, then it cahnge it to `OFFLINE`

**Comment by ghernadi** [comment] 2018-09-05 14:17
Starting the controller or satellite "by hand", you can pass the `-d` option to enable the debug-console. In there you can list the currently open connections, but I'm afraid those 2ms are not really much time to debug...

Regarding the change in online-status: if the satellite does not go into ONLINE state (only from connected -> offline) it might be that the satellite is unhappy with some data it initially received from the controller. That might be the satellite's node-name it gets assigned by the controller (has to match its local `uname -n`), or the version mismatch, etc... Although the version mismatch should be visible via the client as something like `OFFLINE (VERSION MISMATCH)` ...

Can you try deleting and re-adding the node? Or do you have already deployed resources there which would be lost when you delete?
If you could do it, you might have to use the `node lost` command, as a simple delete would require the satellite to be considered as ONLINE :)

**Comment by kvaps** [comment] 2018-09-05 14:31
Well as I said, If I remove any resources from this node it is going to `ONLINE` without any problems.
Here is some problem on deeper level.
By the way I was collected `open` calls via command
```
strace -p -e open `pgrep -f satellite` 2>&1 | tee /tmp/stace_log_open.txt
```
[stace_log_open.txt](https://github.com/LINBIT/linstor-server/files/2353172/stace_log_open.txt)
It's things a lot on:
```
open("/dev/drbd1004",
```
```

**Comment by kvaps** [comment] 2018-09-05 14:37
> Can you try deleting and re-adding the node?
Yes it is not helping too

**Comment by kvaps** [comment] 2018-09-05 15:49
lvm commands is executing slow, not because iscsi, it is because node have block device which is corrently secondary :-/

**Comment by raltnoeder** [comment] 2018-09-05 17:29
The controllers and satellites normally log their connections. It would probably make sense to run both of them in the foreground, to watch what's going on.
If a controller port is reachable on the internet (or forwarded correctly), we could also add some database entries to create a privileged identity and configure an SSL connector, so we could remotely debug the controller.

**Comment by kvaps** [comment] 2018-09-05 18:38
@raltnoeder, well, if you don't mind I can organize that
Np, it's just testing instance for me, please let me know your external IP address where you will connect from, I'llconfigure nat to the linstor controller and linstor-satellites for you.

nice trick:
```
curl icanhazip.com
```

**Comment by kvaps** [comment] 2018-09-06 07:13
Yes, nodes are going OFFLINE immediately after placing resources on them, they will marked like ONLINE only after I manually switch some device into primary mode:
```
drbdadm primary <resource> --force
drbdadm secondary <resource>
```
It also working if I'll just remove resource from the node, then restart linstor satellite

**Comment by ghernadi** [comment] 2018-09-06 09:12
There is some kind of "panic-connection-closing" mechanism in the satellite's method which applies the data received from the controller. However, the command right before the `connection.close()` actually generates an ErrorReport. 

I'd suggest the same as robert suggested, namely running at least the satellite (or also the controller) in foreground and simply watch the output of the processes if anything suspicious occurs. You could also increase the log-level to DEBUG or even TRACE in the `logback.xml` located in `/usr/share/linstor-server/lib/conf/`

**Comment by kvaps** [comment] 2018-09-06 10:58
@ghernadi thanks for info, about how to improve logging...

Now, I've done the next steps.

* cleaned old failed resources
* Reduced number of satellites to 1
* Changed number of replicas to 1
* Enabled TRACE for linstor-controller and linstor-satellite
* Run both services linstor-controller and linstor-satellite in foreground and coolect output

then I create new proxmox VM:

[controller-trace.log](https://github.com/LINBIT/linstor-server/files/2356681/controller-trace.log)
[satellite-trace.log](https://github.com/LINBIT/linstor-server/files/2356682/satellite-trace.log)

Ok node is going offline:
Switch down satellite and controller then start it again:

[satellite_trace2.txt](https://github.com/LINBIT/linstor-server/files/2356687/satellite_trace2.txt)
[controller-trace2.log](https://github.com/LINBIT/linstor-server/files/2356688/controller-trace2.log)

node is still OFFLINE, but seems controller is doing something and execute some command on the satellite, I don't see any error messages there

**Comment by kvaps** [comment] 2018-09-06 11:54
I've got some error report!

*Creating new resource from the scratch*

[controller-trace5.log](https://github.com/LINBIT/linstor-server/files/2356871/controller-trace5.log)
[satellite_trace5.txt](https://github.com/LINBIT/linstor-server/files/2356873/satellite_trace5.txt)
[ErrorReport-5B911484-000000.log](https://github.com/LINBIT/linstor-server/files/2356877/ErrorReport-5B911484-000000.log)

**Comment by kvaps** [comment] 2018-09-06 12:34
@ghernadi thanks,
presume I can made a mistake with `satellite-trace.log` and copy wrong log
please look into *controller-trace5.log* and *satellite_trace5.txt* instead
- there is just one node and just one resource exactly

**Comment by ghernadi** [comment] 2018-09-06 12:50
After a quick look at `controller-trace5.log` and `satellite_trace5.txt` here is what wonders me (nothing really special):
* the unexpected disconnect at the end of both
* a very different local-time of the two machines
* very long execution times from `vgs` commands at the end of the satellite.

After the logs, the satellite is now offline? and stays offline or does the controller reconnect to it?

**Comment by kvaps** [comment] 2018-09-06 13:15
1. as services was running in foregroud, the logs ended up when I pressed Ctrl+C after a while
2. I wrote there wasn't set timezone for controller container, already fixed, problem is not here :(
3. very long execution because of existing non operable drbd device right now:

```
# drbdadm status
test role:Secondary
  disk:Inconsistent

# strace -e open vgs
...
open("/dev/drbd1000", O_RDONLY|O_DIRECT|O_NOATIME) = -1 EMEDIUMTYPE (Wrong medium type)
open("/dev/drbd1000", O_RDONLY|O_NOATIME) = -1 EMEDIUMTYPE (Wrong medium type)
...
```

bascally If I leave both of them for a while I see the next messages on the controller:

```
13:10:28.828 [PlainConnector] DEBUG LINSTOR/Controller - Sending authentication to satellite 'pve1-3'
13:10:31.189 [MainWorkerPool-1] DEBUG LINSTOR/Controller - Start handling API call LstStorPool
13:10:31.190 [MainWorkerPool-1] TRACE LINSTOR/Controller - Running in scope of ApiCall 'LstStorPool' from 10.28.36.161:50000 start
13:10:31.190 [MainWorkerPool-1] TRACE LINSTOR/Controller - Running in scope of ApiCall 'LstStorPool' from 10.28.36.161:50000 finished
13:10:31.190 [MainWorkerPool-1] TRACE LINSTOR/Controller - Running in scope of ApiCall 'LstStorPool' from 10.28.36.161:50000 start
13:10:31.190 [MainWorkerPool-1] TRACE LINSTOR/Controller - Running in scope of ApiCall 'LstStorPool' from 10.28.36.161:50000 finished
13:10:35.828 [TaskScheduleService] TRACE LINSTOR/Controller - Connection to Node: 'pve1-3' lost. Removed from pingList, added to reconnectList.
13:10:35.828 [TaskScheduleService] TRACE LINSTOR/Controller - Event 'connection closed' start: Node: 'pve1-3'
13:10:35.828 [TaskScheduleService] TRACE LINSTOR/Controller - Event 'connection closed' end: Node: 'pve1-3'
13:10:35.829 [TaskScheduleService] TRACE LINSTOR/Controller - Running in scope of ApiCall 'LstStorPool' from 10.28.36.161:50000 start
13:10:35.829 [TaskScheduleService] TRACE LINSTOR/Controller - Running in scope of ApiCall 'LstStorPool' from 10.28.36.161:50000 finished
```

I attach more long period log file where controller can't connect to the satellite, until it have `test` resource, it shows like OFFLINE (time is fixed there)

[satellite-trace6.log](https://github.com/LINBIT/linstor-server/files/2357163/satellite-trace6.log)
[controller-trace6.log](https://github.com/LINBIT/linstor-server/files/2357165/controller-trace6.log)

**Comment by ghernadi** [comment] 2018-09-06 14:01
Okay, somehow "good news" here: I was able to reproduce your issue .... :tada: 
The "not so good news" is that the reproduction includes something like this in our "ExternalCommandExecutor" class:
```
if (command[0].equals("vgs"))
{
    try
    {
        Thread.sleep(5_000);
    }
    catch (InterruptedException exc)
    {
        exc.printStackTrace();
    }
}
```
With this code-snippet added, I get pretty much the same behaviour as you show in your log files. 

In summary: I agree that we will need to investigate why the connection breaks down when the "vgs" command (or other external commands) take too long. 

Until then, you might want to configure your lvm.conf in a way that lvm should exclude all devices except the actual PVs, This should speed up your vgs command even when having a drbd device running.

**Comment by kvaps** [comment] 2018-09-06 14:09
Good news,
I was glad to help you, you're making nice piece of software, thanks! :)

**Comment by kvaps** [comment] 2018-09-06 15:39
Adding `/dev/drbd.*` into `global_filter` is usable workaround for this issue now:

quick command for achieve this:
```
sed -i '/^[^#]*global_filter *=/ s/ *] *$/, "r|\/dev\/drbd.*|" ]/' /etc/lvm/lvm.conf
```

**Closed** 2019-03-19 13:28 UTC
