### ISSUE TITLE
linstor error-report show xxx fails if output is piped/redirected 

### ISSUE THREAD

**Issue by gy-lehel** [LINBIT/linstor-server#13] opened 2018-09-14 07:43 UTC
linstor error-reports show 5B9A4EE9-000002 | tee /home/test/5B9A4EE9-000002
Traceback (most recent call last):
  File "/usr/bin/linstor", line 24, in <module>
    linstor_client_main.main()
  File "/usr/lib/python2.7/dist-packages/linstor_client_main.py", line 555, in main
    LinStorCLI().run()
  File "/usr/lib/python2.7/dist-packages/linstor_client_main.py", line 521, in run
    sys.exit(self.parse_and_execute(sys.argv[1:]))
  File "/usr/lib/python2.7/dist-packages/linstor_client_main.py", line 264, in parse_and_execute
    rc = args.func(args)
  File "/usr/lib/python2.7/dist-packages/linstor_client/commands/commands.py", line 759, in cmd_error_report
    return self.output_list(args, lstmsg, self.show_error_report, single_item=False)
  File "/usr/lib/python2.7/dist-packages/linstor_client/commands/commands.py", line 226, in output_list
    output_func(args, replies[0].proto_msg if single_item else replies)
  File "/usr/lib/python2.7/dist-packages/linstor_client/commands/commands.py", line 755, in show_error_report
    print(error.text)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xae' in position 134: ordinal not in range(128)

**Comment by gy-lehel** [comment] 2018-09-14 07:45
Ubuntu server 18.04
linstor-client-0.6.1.tar.gz  linstor-server-0.6.3.tar.gz  python-linstor-0.6.1.tar.gz

**Comment by rp-** [comment] 2018-09-14 08:04
Thanks looking into it

**Comment by forfreeuser** [comment] 2018-09-14 10:15
workaround: install linstor-controller  instead of  linstor-server.

**Comment by rck** [comment] 2018-09-14 13:07
@forfreeuser Why would that help? Why would that have anything todo with controller vs. server? Spoiler: it is completely unrelated. But as I don't want users be confused by that, here we go:
- linstor-server is the name of the tarball.
- From that we generate packages, these are called linstor-common, linstor-satellite, linstor-controller
- In the very very early days there have been linstor-server packages (before I did the package split). If you have such a package, don't use it,it is ways outdated.

The actual problem has nothing to do with that. The problem is that error reports contain an UTF-8 rune. And if you pipe that, Python 2's (not 3) default encoding switches to ASCII and then "print" breaks.

This is fixed in the client internally.

**Closed** 2018-10-02 08:37 UTC
