### ISSUE TITLE
A bunch of errors after restart 

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#59] opened 2019-06-13 14:57 UTC
Sometimes if I restart the linstor-controller, and if I immediately run `linstor r l` command, I'll get a bunch of errors:

```
...
ERROR:
Description:
    Node: 'm1c6', resource: 'one-vm-128-disk-0', volume: 0 - Device provider threw a storage exception
Details:
    Command 'blockdev --getsize64 /dev/data/one-image-46_00000' returned with exitcode 1. 
    
    Standard out: 
    
    
    Error message: 
    blockdev: cannot open /dev/data/one-image-46_00000: No such file or directory
    
ERROR:
Description:
    Node: 'm1c6', resource: 'one-image-30', volume: 0 - Device provider threw a storage exception
Details:
    Command 'blockdev --getsize64 /dev/data/one-image-46_00000' returned with exitcode 1. 
    
    Standard out: 
    
    
    Error message: 
    blockdev: cannot open /dev/data/one-image-46_00000: No such file or directory
    
ERROR:
Description:
    Node: 'm1c6', resource: 'one-image-40', volume: 0 - Device provider threw a storage exception
Details:
    Command 'blockdev --getsize64 /dev/data/one-image-46_00000' returned with exitcode 1. 
    
    Standard out: 
    
    
    Error message: 
    blockdev: cannot open /dev/data/one-image-46_00000: No such file or directory
    
ERROR:
Description:
    Node: 'm1c6', resource: 'one-vm-113-disk-2', volume: 0 - Device provider threw a storage exception
Details:
    Command 'blockdev --getsize64 /dev/data/one-image-46_00000' returned with exitcode 1. 
    
    Standard out: 
    
    
    Error message: 
    blockdev: cannot open /dev/data/one-image-46_00000: No such file or directory
    
```

But after ~ten seconds it starts working as it should

**Comment by kvaps** [comment] 2019-06-13 14:59
UPD: this behavior can be reproduced and without restart controller

**Comment by raltnoeder** [comment] 2019-06-14 11:14
Yet another race condition in the operating system that LINSTOR needs to workaround somehow, we'll investigate it.

**Comment by kvaps** [comment] 2019-06-14 15:23
@raltnoeder I'm not sure that it is fully operation system problem, the weird thing is that I see these errors not for some resources of output but exactly for the every one, running on all the nodes.

**Comment by raltnoeder** [comment] 2019-06-14 22:55
Well, you reported:
```
Command 'blockdev --getsize64 /dev/data/one-image-46_00000' returned with exitcode 1.
blockdev: cannot open /dev/data/one-image-46_00000: No such file or directory
```
and
> But after ~ten seconds it starts working as it should

Seems pretty much like a system error to me, since it's an external command that is failing, and then, after some time, it suddenly doesn't fail anymore, apparently because of some kind of race condition in the system.

**Comment by kvaps** [comment] 2019-06-15 16:12
I agree that it is system error, but this error has occurred only with single device `/dev/data/one-image-46_00000`, and reported multiple times for each other resource also.

**Comment by ghernadi** [comment] 2019-06-18 05:54
> UPD: this behavior can be reproduced and without restart controller

Can you show the steps needed to reproduce this issue?

**Comment by rp-** [comment] 2022-06-02 07:16
closing, please reopen if it could be reproduced

**Closed by rp-** 2022-06-02 07:16 UTC
