### ISSUE TITLE
Updating default interface IP puts node OFFLINE

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#226] opened 2021-04-21 13:37 UTC
```
# linstor n l -n m1c37
╭──────────────────────────────────────────────────────╮
┊ Node  ┊ NodeType  ┊ Addresses               ┊ State  ┊
╞══════════════════════════════════════════════════════╡
┊ m1c37 ┊ SATELLITE ┊ 10.28.36.176:3367 (SSL) ┊ Online ┊
╰──────────────────────────────────────────────────────╯
```

```
# linstor n i l m1c37
╭─────────────────────────────────────────────────────────────────╮
┊ m1c37     ┊ NetInterface ┊ IP           ┊ Port ┊ EncryptionType ┊
╞═════════════════════════════════════════════════════════════════╡
┊ + StltCon ┊ default      ┊ 10.28.36.176 ┊ 3367 ┊ SSL            ┊
╰─────────────────────────────────────────────────────────────────╯
```

```bash
# linstor n i m m1c37 default --ip 10.28.36.176
SUCCESS:
Description:
    NetInterface 'default' on node 'm1c37' modified.
Details:
    NetInterface 'default' on node 'm1c37' UUID is: 4bef0401-21a3-483e-a836-a59848d1d9ed
```

```bash
# linstor n l -n m1c37
╭───────────────────────────────────────────────────────╮
┊ Node  ┊ NodeType  ┊ Addresses               ┊ State   ┊
╞═══════════════════════════════════════════════════════╡
┊ m1c37 ┊ SATELLITE ┊ 10.28.36.176:3367 (SSL) ┊ OFFLINE ┊
╰───────────────────────────────────────────────────────╯
```

also `linstor node reconnect` feature never working:
```bash
# linstor n reconnect m1c37
WARNING:
    Nodes [] are evicted and will not be reconnected. Use node restore <node-name> to reconnect.
```

restart of linstor-controller solves this issue

**Comment by ghernadi** [comment] 2021-04-21 14:21
<details><summary>I was not able to reproduce the issue above using Linstor 1.11.1</summary>

```
linstor n c --communication-type ssl bravo
linstor --no-utf8 --no-color n l
+-------------------------------------------------------+
| Node  | NodeType  | Addresses                | State  |
|=======================================================|
| bravo | SATELLITE | 192.168.1.110:3367 (SSL) | Online |
+-------------------------------------------------------+

linstor --no-utf8 --no-color n i l bravo
+------------------------------------------------------------------+
| bravo     | NetInterface | IP            | Port | EncryptionType |
|==================================================================|
| + StltCon | default      | 192.168.1.110 | 3367 | SSL            |
+------------------------------------------------------------------+

linstor n i m --ip 192.168.1.110 bravo default
linstor --no-utf8 --no-color n l
+--------------------------------------------------------+
| Node  | NodeType  | Addresses                | State   |
|========================================================|
| bravo | SATELLITE | 192.168.1.110:3367 (SSL) | OFFLINE |
+--------------------------------------------------------+

linstor --no-utf8 --no-color n i l bravo
+------------------------------------------------------------------+
| bravo     | NetInterface | IP            | Port | EncryptionType |
|==================================================================|
| + StltCon | default      | 192.168.1.110 | 3367 | SSL            |
+------------------------------------------------------------------+

sleep 15.0s
linstor --no-utf8 --no-color n l
+-------------------------------------------------------+
| Node  | NodeType  | Addresses                | State  |
|=======================================================|
| bravo | SATELLITE | 192.168.1.110:3367 (SSL) | Online |
+-------------------------------------------------------+

linstor --no-utf8 --no-color n i l bravo
+------------------------------------------------------------------+
| bravo     | NetInterface | IP            | Port | EncryptionType |
|==================================================================|
| + StltCon | default      | 192.168.1.110 | 3367 | SSL            |
+------------------------------------------------------------------+
```

</details>

The controller might wait up to 10 seconds before it starts reconnecting... maybe you were simply not patient enough? 

> also linstor node reconnect feature never working:

That is actually only a bug that the wrong warning is printed, the actual reconnect should happen in the background as expected. This wrong message will be fixed in the next release.

**Comment by kvaps** [comment] 2021-04-21 18:08
@ghernadi, I'm pretty sure about that

```
# linstor n l -n m1c37
╭──────────────────────────────────────────────────────╮
┊ Node  ┊ NodeType  ┊ Addresses               ┊ State  ┊
╞══════════════════════════════════════════════════════╡
┊ m1c37 ┊ SATELLITE ┊ 10.28.36.176:3367 (SSL) ┊ Online ┊
╰──────────────────────────────────────────────────────╯
# linstor n i m m1c37 default --ip 10.28.36.176
SUCCESS:
Description:
    NetInterface 'default' on node 'm1c37' modified.
Details:
    NetInterface 'default' on node 'm1c37' UUID is: 4bef0401-21a3-483e-a836-a59848d1d9ed
# linstor n l -n m1c37
╭───────────────────────────────────────────────────────╮
┊ Node  ┊ NodeType  ┊ Addresses               ┊ State   ┊
╞═══════════════════════════════════════════════════════╡
┊ m1c37 ┊ SATELLITE ┊ 10.28.36.176:3367 (SSL) ┊ OFFLINE ┊
╰───────────────────────────────────────────────────────╯
# date
2021-04-21T20:04:38 CEST
# date
2021-04-21T20:04:52 CEST
# linstor n l -n m1c37
╭───────────────────────────────────────────────────────╮
┊ Node  ┊ NodeType  ┊ Addresses               ┊ State   ┊
╞═══════════════════════════════════════════════════════╡
┊ m1c37 ┊ SATELLITE ┊ 10.28.36.176:3367 (SSL) ┊ OFFLINE ┊
╰───────────────────────────────────────────────────────╯
# linstor c v
linstor controller 1.11.1; GIT-hash: fe95a94d86c66c6c9846a3cf579a1a776f95d3f4
```

I can append that sometimes our production nodes become `OFFLINE` by themselfs, and can't be moved back `Online` until linstor-controller restart.

**Comment by ghernadi** [comment] 2021-04-21 18:12
In that case please check for ErrorReports from those satellites that stay in `OFFLINE` state (once they are back online of course) or ErrorReports from the controller itself during that timeframe. Possible that something has killed / crashed the TCP thread of either the controller or the satellite, but I'd be interested in what root cause is..

"Sometimes nodes go offline" is not really something I can work with easily :)

**Closed** 2022-06-02 09:19 UTC
