### ISSUE TITLE
All numbers in the range [0 - 31] are occupied

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#107] opened 2020-02-13 13:44 UTC
Hello, just faced with the unavailability to create new replicas for the resource

```bash
# linstor r c m12c9 hosting-mx8-vol-data-mail-wes1-mx8-0 --diskless
ERROR:
Description:
    No TCP/IP port number could be allocated for the resource
Cause:
    The pool of free TCP/IP port numbers is exhausted
    All numbers in the range [0 - 31] are occupied
Correction:
    - Adjust the TcpPortAutoRange controller configuration value to extend the range
      of TCP/IP port numbers used for automatic allocation
    - Delete unused resource definitions that occupy TCP/IP port numbers from the range
      used for automatic allocation
Details:
    Node(s): 'm12c9', Resource: 'hosting-mx8-vol-data-mail-wes1-mx8-0'
Show reports:
    linstor error-reports show 5E43DCC1-00000-000288
```

[5E43DCC1-00000-000288.log](https://github.com/LINBIT/linstor-server/files/4198634/5E43DCC1-00000-000288.log)

This is not connected with the `TcpPortAutoRange`
```bash
# linstor vd l | wc -l
1782
# linstor c lp | grep -i tcp
| TcpPortAutoRange                          | 55000-59999          |

**Comment by ghernadi** [comment] 2020-02-13 13:47
I agree, the error message is misleading.. that should not complain about TCP/IP port range, but about node-id range... how many resources do you have from that resource-definition?

**Comment by kvaps** [comment] 2020-02-13 13:49
>  how many resources do you have from that resource-definition?

just two of them:

```
linstor r l -r hosting-mx8-vol-data-mail-wes1-mx8-0 -a
+-------------------------------------------------------------------------+
| ResourceName                         | Node  | Port | Usage  |    State |
|=========================================================================|
| hosting-mx8-vol-data-mail-wes1-mx8-0 | m12c5 | 7005 | Unused | UpToDate |
| hosting-mx8-vol-data-mail-wes1-mx8-0 | m7c8  | 7005 | Unused | UpToDate |
+-------------------------------------------------------------------------+
```

**Comment by ghernadi** [comment] 2020-02-13 13:55
okay... interesting.. I will look into this..

I guess this error occurs always now if you are trying to re-execute the command?
If so, can you try to restart the controller and retry the command?
If that works afterwards as expected, can you try to reproduce this issue? or briefly tell what you did before? (how many diskful resource-creations, controller restarts, ... anything unusual?)

**Comment by kvaps** [comment] 2020-02-13 14:24
@ghernadi it seems after the controller restart it's started working as it should.
I have no exact steps to reproduce, for now it is single case, but I will write here if we will have it again.

**Comment by kvaps** [comment] 2020-02-17 18:32
Just faced with this issue again on another server:

```
Message: 'No TCP/IP port number could be allocated for the resource'; Cause: 'The pool of free TCP/IP port numbers is exhausted
All numbers in the range [0 - 31] are occupied
'; Details: 'Node(s): 'm1c5', Resource: 'pvc-ad89d525-a87e-4c89-9cd3-b513236ee0ea''; Correction: '- Adjust the TcpPortAutoRange controller configuration value to extend the range
  of TCP/IP port numbers used for automatic allocation
- Delete unused resource definitions that occupy TCP/IP port numbers from the range
  used for automatic allocation
'; Reports: '[5E414B7A-00000-000961]
```

Not sure that it is connected but previously I was updating `Aux/csi-volume-annotations` properties for each resource, s Linstor was calling adjust operation for each one.

```
SUCCESS:
Description:
    Resource definition 'pvc-f8aa2cba-8784-4a21-b8c1-fc192272d8d9' modified.
Details:
    Resource definition 'pvc-f8aa2cba-8784-4a21-b8c1-fc192272d8d9' UUID is: e393aba1-d912-40d2-90d3-bf92e6c221ea
SUCCESS:
    (m1c12) Resource 'pvc-f8aa2cba-8784-4a21-b8c1-fc192272d8d9' [DRBD] adjusted.
SUCCESS:
    (m1c4) Resource 'pvc-f8aa2cba-8784-4a21-b8c1-fc192272d8d9' [DRBD] adjusted.
```

**Comment by raltnoeder** [comment] 2020-02-19 18:08
According to the error report, this happens during node id allocation, which basically just collects the node ids of all resources of the current resource definition and feeds it to the com.linbit.linstor.NodeIdAlloc class, which calls com.linbit.NumberAlloc.getFreeNumber() with an array of the occupied numbers and the number limits (0 for smallest and 31 for greatest node id).

I ran the getFreeNumber() algorithm through roughly 20 million randomized tests with 0-32 random node ids being occupied, and it passed all of them, so I guess the algorithm works properly.

Input to this algorithm must be an array of occupied numbers with no duplicates and sorted in ascending order. But even in cases where the array is not sorted, or where duplicates are present (with even more entries than there are valid node ids), I believe the algorithm would return an incorrect result, but would not run into an allocation failure. This is also consistent with a few tests I ran.

The most likely reason for this still seems to be that there is actually a list of occupied numbers supplied to this algorithm where there are no free valid node ids. Now the remaining question is how this list could possibly have been created.

**Comment by ghernadi** [comment] 2020-02-24 07:12
@kvaps: this is nothing more than a wild guess - but when these problems occurred where no more node-ids were available... is it possible that you had a few ERRORs before that trying to create resources within the same resource-definition?

My guess here is that we might screwed up an internal cleanup, leaving "rollbacked" data still within some certain lists which would still be used for the `getFreeNodeId` method. If those still remaining "rollbacked" data sum up to >= 32, this might explain the issue (also why restarting the controller fixes it)

The bug I am suspecting now is already fixed internally and will surely be included in the next release.

**Comment by rp-** [comment] 2020-05-22 08:17
reopen if it still occurs

**Closed by rp-** 2020-05-22 08:17 UTC
